name: Deploy to GitHub Pages

on:
  # Trigger on tag creation
  push:
    tags:
      - 'v*'
    # Also trigger on main branch updates
    branches:
      - main
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Create deployment directory
        run: |
          mkdir -p _site
          
      - name: Copy game files to deployment directory
        run: |
          # Copy main game files
          cp index_complete.html _site/index.html
          cp audioManager.js _site/
          cp game_final.js _site/
          cp style.css _site/
          cp favicon.ico _site/
          
          # Copy additional versions
          cp index.html _site/original.html
          cp index_fixed.html _site/fixed.html
          cp game.js _site/
          cp game_fixed.js _site/
          
          # Copy test suites
          cp test_complete.html _site/test.html
          cp test_audio_system.html _site/
          
          # Copy documentation
          cp README.md _site/
          cp HANDOFF.md _site/
          
          # Copy utility files
          cp start_game.sh _site/
          cp server.py _site/
          
      - name: Create deployment info page
        run: |
          cat > _site/info.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Meow Mi - Game Versions</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      min-height: 100vh;
                  }
                  .container {
                      background: rgba(255,255,255,0.1);
                      padding: 30px;
                      border-radius: 15px;
                      backdrop-filter: blur(10px);
                  }
                  h1 { text-align: center; font-size: 2.5em; margin-bottom: 10px; }
                  .subtitle { text-align: center; margin-bottom: 30px; opacity: 0.9; }
                  .version-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                      gap: 20px;
                      margin: 30px 0;
                  }
                  .version-card {
                      background: rgba(255,255,255,0.15);
                      padding: 20px;
                      border-radius: 10px;
                      text-align: center;
                      transition: transform 0.3s;
                  }
                  .version-card:hover { transform: translateY(-5px); }
                  .version-card h3 { margin-top: 0; color: #ffeb3b; }
                  .btn {
                      display: inline-block;
                      padding: 12px 24px;
                      background: #4CAF50;
                      color: white;
                      text-decoration: none;
                      border-radius: 25px;
                      font-weight: bold;
                      margin: 5px;
                      transition: background 0.3s;
                  }
                  .btn:hover { background: #45a049; }
                  .btn-primary { background: #2196F3; }
                  .btn-primary:hover { background: #0b7dda; }
                  .btn-warning { background: #ff9800; }
                  .btn-warning:hover { background: #e68900; }
                  .footer { text-align: center; margin-top: 40px; opacity: 0.8; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🐱 Meow Mi</h1>
                  <p class="subtitle">2D Side-Scrolling Cat Runner Game</p>
                  
                  <div class="version-grid">
                      <div class="version-card">
                          <h3>🎮 Main Game</h3>
                          <p>Complete version with fixed audio system and enhanced features.</p>
                          <a href="index.html" class="btn">Play Now</a>
                      </div>
                      
                      <div class="version-card">
                          <h3>🧪 Test Suite</h3>
                          <p>Comprehensive audio testing and debugging tools.</p>
                          <a href="test.html" class="btn btn-primary">Run Tests</a>
                      </div>
                      
                      <div class="version-card">
                          <h3>📊 Audio Tests</h3>
                          <p>Detailed audio system testing interface.</p>
                          <a href="test_audio_system.html" class="btn btn-warning">Audio Tests</a>
                      </div>
                      
                      <div class="version-card">
                          <h3>🕹️ Original Version</h3>
                          <p>The original game version before audio fixes.</p>
                          <a href="original.html" class="btn">Original Game</a>
                      </div>
                      
                      <div class="version-card">
                          <h3>🔧 Fixed Version</h3>
                          <p>Intermediate version with partial audio fixes.</p>
                          <a href="fixed.html" class="btn">Fixed Version</a>
                      </div>
                  </div>
                  
                  <div class="footer">
                      <p>Built with Phaser 3 • Enhanced Audio System • Open Source</p>
                      <p>🤖 Generated with <a href="https://claude.ai/code" style="color: #ffeb3b;">Claude Code</a></p>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Create deployment summary
        run: |
          echo "## 🚀 Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🎮 **Game URL**: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Available Pages:" >> $GITHUB_STEP_SUMMARY
          echo "- 🎮 [Main Game](${{ steps.deployment.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY
          echo "- 📋 [All Versions](${{ steps.deployment.outputs.page_url }}info.html)" >> $GITHUB_STEP_SUMMARY
          echo "- 🧪 [Test Suite](${{ steps.deployment.outputs.page_url }}test.html)" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 [Audio Tests](${{ steps.deployment.outputs.page_url }}test_audio_system.html)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🏷️ **Tag**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY